/**
 * ChooseLab — AI-powered Choose Your Own Adventure for kids
 *
 * State machine:
 *   idle → picking → generating-arc → arc-ready → playing → ending → finished
 *
 * Each "panel" represents one beat of the story. A panel has illustration,
 * narration audio, ambient sound, character thought bubble, and 2-3 choices.
 * The kid picks a choice → the next panel generates. After 5 panels, the
 * climax panel triggers a gen4_turbo animation, then the ending.
 */

export interface Setting {
  id: string;
  label: string;
  emoji: string;
  description: string;
  visualPaletteHint: string;
}

export interface Hero {
  id: string;
  label: string;
  emoji: string;
  description: string;
  appearanceHint: string;
}

export interface Problem {
  id: string;
  label: string;
  emoji: string;
  description: string;
}

export interface AdventureSeed {
  setting: Setting;
  hero: Hero;
  problem: Problem;
}

/** Full story arc generated by the architect call before any panel rendering. */
export interface StoryArc {
  title: string;
  hero: {
    name: string;
    /** 2-sentence visual description repeated verbatim in every image prompt to lock character consistency. */
    appearanceLock: string;
    voiceTrait: string;
  };
  worldDescription: string;
  moralTheme: string;
  ageBand: '5-7' | '8-10';
  panels: PanelSpec[];
}

/** Skeleton of a panel — fleshed out into PanelData when the kid arrives at it. */
export interface PanelSpec {
  panelId: string;
  index: number;
  isClimax: boolean;
  beat: string;
  emotionalTone: string;
  /** Set when the kid reaches this panel. */
  precedingChoiceId?: string;
}

/** Full data for one rendered panel — what the UI displays. */
export interface PanelData {
  panelId: string;
  index: number;
  isClimax: boolean;
  narratorText: string;
  thoughtBubble: string;
  imageUrl: string;
  videoUrl?: string;
  narrationAudioUrl: string;
  ambientSoundUrl: string;
  choices: Choice[];
}

export interface Choice {
  id: string;
  label: string;
  rationale: string;
}

export interface AdventureSession {
  sessionId: string;
  seed: AdventureSeed;
  arc: StoryArc;
  panelHistory: PanelData[];
  currentPanelIndex: number;
  finished: boolean;
}

export type AdventureStage =
  | { stage: 'idle' }
  | { stage: 'picking' }
  | { stage: 'generating-arc'; seed: AdventureSeed }
  | { stage: 'arc-ready'; session: AdventureSession }
  | { stage: 'rendering-panel'; session: AdventureSession; panelIndex: number }
  | { stage: 'playing'; session: AdventureSession }
  | { stage: 'finished'; session: AdventureSession }
  | { stage: 'error'; message: string };
